version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL} # Set the DB URL to connect to the Postgres container
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - wedding_network
  
  db:
    image: postgres:13 # Use the official PostgreSQL image
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_DB=wedding_db
    volumes:
      - postgres_data:/var/lib/postgresql/data # Volume to persist database data
    ports:
      - "5432:5432"
    networks:
      - wedding_network


networks:
  wedding_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
